package com.soyle.stories.characterarc.unlinkLocationFromCharacterArcSection

interface UnlinkLocationFromCharacterArcSectionController {

	fun unlinkLocationFromCharacterArcSection(sectionId: String)
}