package com.soyle.stories.location.hostedScene.hostScene

import com.soyle.stories.scene.locationsInScene.linkLocationToScene.LinkLocationToSceneController

typealias HostSceneController = LinkLocationToSceneController