name: "\U0001F41E Bug report"
description: Report a bug in Soyle Stories
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: ✍️ Description
      description: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🔬 Minimal Reproduction
      description: Clear steps to re-produce the issue.
      placeholder: |
        1. Create a new project named "..."
        2. Create a character named "..."
        3. ...
        4. Final step before bug was encountered
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Result
      description: What should have happened after that final step?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Result
      description: What actually happened after that final step?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
