package com.soyle.stories.characterarc.baseStoryStructure

import com.soyle.stories.characterarc.changeSectionValue.ChangedCharacterArcSectionValueReceiver
import com.soyle.stories.usecase.character.viewBaseStoryStructure.ViewBaseStoryStructure
import com.soyle.stories.usecase.location.listAllLocations.ListAllLocations

interface BaseStoryStructureEventReceiver  : ViewBaseStoryStructure.OutputPort, ListAllLocations.OutputPort,
    ChangedCharacterArcSectionValueReceiver