name: detekt

on:
  push:
    branches: [ main ]

 jobs:
   detekt:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "detekt"
         uses: natiginfo/action-detekt-all@1.17.1
         with:
          args: --fail-fast --config detekt.yml
